openapi: 3.1.0
info:
  title: NLIP API
  version: "1.0.0"
servers:
  - url: http://localhost:8004/nlip
paths:
  /ping:
    get:
      summary: health
      operationId: pingNLIP
      responses:
        "200":
          description: pong
          content:
            text/plain:
              schema:
                type: string
  /chat:
    get:
      summary: relay chat
      operationId: chatNLIP
      parameters:
        - name: q
          in: query
          schema:
            type: string
          required: false
      responses:
        "200":
          description: reply
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    AllowedFormat:
      type: string
      enum:
        - text
        - token
        - structured
        - binary
        - location
        - generic
    NLIPSubMessage:
      type: object
      required:
        - format
        - subformat
        - content
      properties:
        format:
          $ref: "#/components/schemas/AllowedFormat"
        subformat:
          type: string
        content:
          type: string
        label:
          type: string
    NLIPRequest:
      type: object
      required:
        - format
        - subformat
        - content
      properties:
        messagetype:
          type: string
          enum:
            - control
        format:
          $ref: "#/components/schemas/AllowedFormat"
        subformat:
          type: string
        content:
          type: string
        submessages:
          type: array
          items:
            $ref: "#/components/schemas/NLIPSubMessage"
